### ISSUE TITLE
mude output

### ISSUE THREAD

**Issue by kcdtv** [devttys0/wps#1]
thank you for sharing with us your tool kit for WPS
I downloaded and installed scapy successfully and got wpsscan.py working perfectly
i gave permissions to the python script with chmod +x and chmod 777
As i used xubuntu 64 amd i launched the script with "sudo" and tryed with ./ or by invoking python.
i tryed with network manager enabled and with network manger stooped.
I also "ifconfig up" my interface (internal common chipset by atheros with ath5k driver, perfectly supported) 
In every case i got the same results 
" sudo python wpspy.py -i wlan0 -v"  or  "sudo ./wpspy.py -i wlan0 -v"
WARNING: No route found for IPv6 destination :: (no default route?)

Listening on wlan0..."
and nothing happens...
I have the same warning about ipv6 route in wpsscan but it is not a problem with wpsscan...
Maybe i missed something? Does the scrypt requires things like pylorcon2? 
cheers.

**Comment by devttys0** [comment]
The `No route found for IPv6 destination :: (no default route?)` warning is a scapy thing and doesn't affect the operation of either script.

If `wpspy` isn't spitting out any information, that means that it's not seeing any 802.11 management frames that advertise WPS support. 

It could be that there are no WPS enabled AP's in your area. 

It could be that there are, but they aren't transmitting on the channel that your wireless interface is on (neither script will channel hop, but you can run `airodump-ng` at the same time as an easy way to hop channels).

You mentioned that you did an `ifconfig up` on your interface, but not that you put the interface into monitor mode. Are you sure your `wlan0` interface is in monitor mode?

The `wpscan.py` script is an active tool, e.g., it will actively send probe request packets to access points. That may work better for you than `wpspy.py`, depending on your situation.

**Comment by kcdtv** [comment]
Good afternoon 

" You mentioned that you did an ifconfig up on your interface, but not that you put the interface into monitor mode. Are you sure your wlan0 interface is in monitor mode?. "

   ....Well... I am 100% sure that it is not in mode monitor :D 
As wpspy.py is a passive scanner; I thought that monitor mode was not a requirement for this script ( like for something like "iw <dev> scan" or "wpa_cli" ), 
I should have looked more into the code and tried with monitor mode  before posting an issue :P

 Conclusion : it worked perfectly as son as i activated the mode monitor, i didn't even had to specify the interface and didn't need to "wake it up" by launching airodump-ng in another shell

![terminal - kcdtv profezorapplestruff -wps-master-wpstools_144](https://cloud.githubusercontent.com/assets/7338484/7275790/275215d2-e906-11e4-8a1c-b2b8bf443e6b.png)

Thank you for taking the time to answer; I closed the "issue" as there is no "issue" :smile:
